apiVersion: v1
kind: Secret
metadata:
  name: youryummy-{{ .Chart.Name }}-secrets
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}youryummy{{ end }}
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    JWT_SECRET: {{ .Values.global.jwt_secret }}
    JWT_ISSUER: {{ .Values.global.jwt_issuer }}
    MONGO_PWD: {{ .Values.mongo_pwd }}
