apiVersion: v1
kind: Secret
metadata:
  name: youryummy-{{ .Chart.Name }}-secrets
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}youryummy{{ end }}
type: Opaque
stringData:

    # CREDENTIALS (For different services)
    JWT_SECRET: {{ .Values.global.jwt_secret }}
    JWT_ISSUER: {{ .Values.global.jwt_issuer }}
    FIREBASE_KEY: {{ (index .Values .Chart.Name).firebase_key | default .Values.firebase_key | quote}}
    FIREBASE_EMAIL: {{ (index .Values .Chart.Name).firebase_email | default .Values.firebase_email }}
    FIREBASE_BUCKET: {{ (index .Values .Chart.Name).firebase_bucket | default .Values.firebase_bucket }}
    FIREBASE_PROJECT_ID: {{ (index .Values .Chart.Name).firebase_project_id | default .Values.firebase_project_id }}
    {{- if (index .Values .Chart.Name).mongo_pwd}}
    MONGO_PWD: {{ (index .Values .Chart.Name).mongo_pwd | default .Values.mongo_pwd }}
    {{- end}}
