apiVersion: v1
kind: Service
metadata:
  labels:
    app: youryummy-{{ .Chart.Name }}
  name: youryummy-{{ .Chart.Name }}
  namespace: {{ if .Values.global.namespaceOverride }}{{.Values.global.namespaceOverride}}{{ else }}youryummy{{ end }}
spec:
  {{- if eq .Values.global.node_env "development" }}
  type: NodePort
  {{- else }}
  clusterIP: {{ if eq .Values.global.node_env "production" }}10.152.0.3{{ else }}10.152.1.3{{ end }}
  {{- end }}
  ports:
    - name: youryummy-{{ .Chart.Name }}
      port: 80
      protocol: TCP
      targetPort: 80
      {{- if eq .Values.global.node_env "development" }}
      nodePort: 42000
      {{- end }}
  selector:
    app: youryummy-{{ .Chart.Name }}